# Assignment 4

## Q1

In [1]:
import numpy as np

In [2]:
arr1=np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [3]:
arr1+=2
arr1

array([3, 4, 5, 6, 7])

In [4]:
arr1*=3
arr1

array([ 9, 12, 15, 18, 21])

In [5]:
arr1=arr1/2
arr1

array([ 4.5,  6. ,  7.5,  9. , 10.5])

## Q2

In [6]:
#array reverse
arr2=np.array([1,2,3,6,4,5])
arr2=arr2[::-1]
arr2

array([5, 4, 6, 3, 2, 1])

In [7]:
x=np.array([1,2,3,4,5,1,2,1,1,1]) 
y=np.array([1,1,1,2,3,4,2,4,3,3]) 
def mostfreq(arr):
    value,counts=np.unique(arr,return_counts=True)
    index=np.argmax(counts)
    val=value[index]
    print("Most frequent: ",val)
    print("Index: ")
    c=0
    for i in arr:
        if (i==val):
            print(c)
        c=c+1
    return

In [8]:
mostfreq(x)

Most frequent:  1
Index: 
0
5
7
8
9


In [9]:
mostfreq(y)

Most frequent:  1
Index: 
0
1
2


## Q3

In [10]:
arr=np.array([[10,20,30],[40,50,60],[70,80,90]])
arr

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [11]:
arr[0,1]

20

In [12]:
arr[2,0]

70

## Q4

In [13]:
rishabh=np.linspace(10,100,25)
rishabh

array([ 10.  ,  13.75,  17.5 ,  21.25,  25.  ,  28.75,  32.5 ,  36.25,
        40.  ,  43.75,  47.5 ,  51.25,  55.  ,  58.75,  62.5 ,  66.25,
        70.  ,  73.75,  77.5 ,  81.25,  85.  ,  88.75,  92.5 ,  96.25,
       100.  ])

In [14]:
rishabh.ndim

1

In [15]:
rishabh.shape

(25,)

In [16]:
rishabh.size

25

In [17]:
rishabh.dtype

dtype('float64')

In [18]:
rishabh.nbytes

200

In [19]:
rishabh=rishabh.reshape(5,5)
rishabh

array([[ 10.  ,  13.75,  17.5 ,  21.25,  25.  ],
       [ 28.75,  32.5 ,  36.25,  40.  ,  43.75],
       [ 47.5 ,  51.25,  55.  ,  58.75,  62.5 ],
       [ 66.25,  70.  ,  73.75,  77.5 ,  81.25],
       [ 85.  ,  88.75,  92.5 ,  96.25, 100.  ]])

In [20]:
Transpose=rishabh.T
Transpose

array([[ 10.  ,  28.75,  47.5 ,  66.25,  85.  ],
       [ 13.75,  32.5 ,  51.25,  70.  ,  88.75],
       [ 17.5 ,  36.25,  55.  ,  73.75,  92.5 ],
       [ 21.25,  40.  ,  58.75,  77.5 ,  96.25],
       [ 25.  ,  43.75,  62.5 ,  81.25, 100.  ]])

## Q5

In [21]:
ucs420_rishabh=np.array([[10,20,30,40,50,60,70,80,90,15,20,35]]).reshape(3,4)
ucs420_rishabh

array([[10, 20, 30, 40],
       [50, 60, 70, 80],
       [90, 15, 20, 35]])

In [22]:
#mean
ucs420_rishabh.mean()

43.333333333333336

In [23]:
#median
np.median(ucs420_rishabh)

37.5

In [24]:
#maximum
ucs420_rishabh.max()

90

In [25]:
#minimum
ucs420_rishabh.min()

10

In [26]:
#unique values
np.unique(ucs420_rishabh)

array([10, 15, 20, 30, 35, 40, 50, 60, 70, 80, 90])

In [27]:
reshaped_ucs420_rishabh=ucs420_rishabh.reshape(4,3)
reshaped_ucs420_rishabh

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90],
       [15, 20, 35]])

In [28]:
resized_ucs420_rishabh=ucs420_rishabh[:2,:3]
resized_ucs420_rishabh

array([[10, 20, 30],
       [50, 60, 70]])